<a href="https://colab.research.google.com/github/ayeshabaig/Pytorch_Fashion_MNIST/blob/master/Autograd_with_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Autograd with tensors

In [4]:
import torch  

In [5]:
w = torch.randn(4,3, requires_grad=True)

In [6]:
w

tensor([[ 1.3197, -0.6579,  0.8692],
        [ 0.1546,  1.3743,  1.8170],
        [-0.3878, -1.4318, -1.1047],
        [ 0.3489,  0.4067, -1.0971]], requires_grad=True)

In [9]:
w.requires_grad_(False)
w

tensor([[ 1.3197, -0.6579,  0.8692],
        [ 0.1546,  1.3743,  1.8170],
        [-0.3878, -1.4318, -1.1047],
        [ 0.3489,  0.4067, -1.0971]])

In [10]:
w.requires_grad_(True)

tensor([[ 1.3197, -0.6579,  0.8692],
        [ 0.1546,  1.3743,  1.8170],
        [-0.3878, -1.4318, -1.1047],
        [ 0.3489,  0.4067, -1.0971]], requires_grad=True)

In [14]:
y = torch.exp(w)
print(y)

tensor([[3.7424, 0.5179, 2.3850],
        [1.1672, 3.9524, 6.1536],
        [0.6786, 0.2389, 0.3313],
        [1.4175, 1.5018, 0.3338]], grad_fn=<ExpBackward>)


In [15]:
print(y.grad_fn)

In [22]:
outp = y.mean()
print(outp)


tensor(1.8684, grad_fn=<MeanBackward0>)


In [17]:
print(w.grad)

None


In [23]:
outp.backward()

In [24]:
print(w.grad)

tensor([[0.3119, 0.0432, 0.1988],
        [0.0973, 0.3294, 0.5128],
        [0.0565, 0.0199, 0.0276],
        [0.1181, 0.1252, 0.0278]])


In [26]:
print(w.detach())

tensor([[ 1.3197, -0.6579,  0.8692],
        [ 0.1546,  1.3743,  1.8170],
        [-0.3878, -1.4318, -1.1047],
        [ 0.3489,  0.4067, -1.0971]])


In [29]:
print(outp.requires_grad)
with torch.no_grad():
  outp = (w+y).mean()

  print(outp.requires_grad)

True
False
