<a href="https://colab.research.google.com/github/ayeshabaig/Pytorch_Fashion_MNIST/blob/master/Tensors_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors 

In [1]:
import torch

## zeros()

In [3]:
w = torch.zeros(4,3)
w

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

## size() and shape

In [4]:
w.size

<function Tensor.size>

In [5]:
w.shape


torch.Size([4, 3])

## randn() and randn_like()

In [7]:
w = torch.randn(4,3)
w

tensor([[ 0.4463,  0.4414, -0.3801],
        [ 1.0429,  0.9948,  2.3643],
        [-0.9486,  0.8582, -0.0717],
        [-1.2703,  0.4016, -1.6680]])

In [9]:
t = torch.randn_like(w)
t

tensor([[-0.3076, -1.2548, -0.1625],
        [-0.6200,  0.2143, -0.5861],
        [-1.2962,  0.2453,  0.4167],
        [-0.3550,  0.1166,  0.1322]])

In [ ]:
W

## fill_()

In [10]:
w.fill_(1)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

## view()

In [11]:
w

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [14]:
t = w.view(3,4)
t

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [15]:
w.view(3, -1)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## numpy()

In [16]:
w.numpy()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)